### PR TITLE
Quick updates to Unity3D compatibility

### PR DESCRIPTION
**Pull request by Mervill**
Hello!

I have two simple commits that make NLua compile cleanly in Unity3D.

The first omits `BindFlags.cs` from being compiled when `UNITY_3D` is given as a compiler directive. I'm not 100% sure whats going on here, but the short story is that Unity uses it's own fork of an older version of mono.

Seccond, as has been discussed before [https://github.com/NLua/NLua/pull/106#issuecomment-58049417] the line endings of some files have been normalized to prevent the Unity compiler from throwing warnings.

I should also mention that Unity3D recently relaxed it's Indie licence and now allows indie games to load non-C# dll's. Therefore my [Unity3D-NLua](https://github.com/Mervill/Unity3D-NLua) project has ended support for KopiLua. I might resume support for KopiLua later, but I'd prefer to focus on using KeraLua/Native C now that it's available to all Unity users.

Thanks!

### CODE REVIEW

**Comment by viniciusjarina** [comment]
Can one of the admins verify this patch?

**Comment by viniciusjarina** [comment]
Why not simply remove the BindFlags from Unity3D csproj ? :)

**Comment by viniciusjarina** [comment]
@Mervill  ^^^

**Comment by Mervill** [comment]
Ack! Sorry, busy week.

Actually, I've been thinking of creating an sln in this project so that NLua can be precompiled for Unity, but I've not gotten around to it.

When working with uncompiled code, Unity doesn't use project files in the traditional sense, everything included under the magic directory `Assets` is compiled. Using preprocessor directives here is the simplest solution to that problem as I'd like to avoid branching the project or complicating the install process.

Let me know what you think.

**Pull request merged**
