### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by MaxVain**
small change to keep nlua thread-safe

### CODE REVIEW

**Comment by AntonNep** [comment]
Awesome

**Comment by kalin-toshev** [comment]
Thanks for merging. Are we getting a new version of the Nuget package, posted on nuget.org as well?

**Comment by viniciusjarina** [comment]
Hi @kalin-toshev my current CI is not uploading it to nuget automatically.

I can do it manually later this week or during the next weekend. 😔

**Comment by kalin-toshev** [comment]
Thanks viniciusjarina! Let us know when the new package makes it on nuget.org.

**Comment by Artum** [comment]
Is NuGet package still out-dated?

**Comment by viniciusjarina** [comment]
It is :/ didn't have the setup on my machine to build the NuGet easily.

I think the best option is build from source right now.

**Pull request merged**
