### PR TITLE
fix #297 (LuaMethodWrapper.CallInvokeOnGenericMethod works with errors )

### LINKED ISSUE #297: LuaMethodWrapper.CallInvokeOnGenericMethod works with errors
Lua.RegisterFunction helps us to register non-generic and generic functions. It works fine if all function arguments are non-generic or all generic. However, we can create functions like this
`public void GenericMethodWithCommonArgs<U>(int x, int y, U z)`
In this situation we will get an exception
`ArgumentException: Incorrect length
System.Reflection.MonoMethod.MakeGenericMethod (System.Type[] methodInstantiation) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
NLua.Method.LuaMethodWrapper.CallInvokeOnGenericMethod (KeraLua.Lua luaState, System.Reflection.MethodInfo methodToCall, System.Object targetObject) (at <b3d9dd7ee9f24eea95427e6522d11d3d>:0)
NLua.Method.LuaMethodWrapper.Call (System.IntPtr state) (at <b3d9dd7ee9f24eea95427e6522d11d3d>:0)
NLua.MetaFunctions.RunFunctionDelegate (System.IntPtr luaState) (at <b3d9dd7ee9f24eea95427e6522d11d3d>:0)
KeraLua.Lua.PCall (System.Int32 arguments, System.Int32 results, System.Int32 errorFunctionIndex) (at <88844d0454ff4fa5b328d32e104372d4>:0)
NLua.Lua.CallFunction (System.Object function, System.Object[] args, System.Type[] returnTypes) (at <b3d9dd7ee9f24eea95427e6522d11d3d>:0)
NLua.Lua.CallFunction (System.Object function, System.Object[] args) (at <b3d9dd7ee9f24eea95427e6522d11d3d>:0)
NLua.LuaFunction.Call (System.Object[] args) (at <b3d9dd7ee9f24eea95427e6522d11d3d>:0)`

### PR DESCRIPTION
**Pull request by Rolemancer**

### CODE REVIEW

**Comment by viniciusjarina** [comment]
That's greate @Rolemancer 
Can you also provide a unit test, so we avoid a regression? Thank you

**Comment by Rolemancer** [comment]
I wrote the test, but have a trouble with tests running. Because when I run any test from solution , I always get the same error
T```
est Name:	TestGenerics
Test FullName:	NLuaTest.LuaTests.TestGenerics
Test Outcome:	Failed
Test Duration:	0:00:00.05

Result StackTrace:	
at KeraLua.NativeMethods.luaL_newstate()
   at KeraLua.Lua..ctor(Boolean openLibs)
   at NLua.Lua..ctor() in C:\Users\Volkov\Documents\Repositories\NLua\src\Lua.cs:line 238
   at NLuaTest.LuaTests.TestGenerics() in C:\Users\Volkov\Documents\Repositories\NLua\tests\src\LuaTests.cs:line 446
Result Message:	System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

```
Can you explain how to setup solution setting to fix the problem?

**Comment by viniciusjarina** [comment]
Your VS is probably trying to run the tests using `x64`, and the `lua53.dll` at the output folder is `x86`. You try to change your test settings to run on `x86`
Screen Shot 2019-05-27 at 11 32 35 AM

**Comment by Rolemancer** [comment]
No, that thing didn't solve the problem :(

**Comment by viniciusjarina** [comment]
Fixed in https://github.com/NLua/NLua/releases/tag/v1.4.21

**Pull request closed without merging**
