### PR TITLE
Add FinishExecution event

### PR DESCRIPTION
**Pull request by Fraysa**
Added an event that is raised when the script has execution.

### CODE REVIEW

**Comment by viniciusjarina** [comment]
Can one of the admins verify this patch?

**Comment by viniciusjarina** [comment]
Hello @Fraysa 

What is the idea behind this event? Also this seems odd why trigger the event after DoFile and After LoadFile? they have different semantics :cry: 

What is the advantage for the current NLua users to have this event ?

**Comment by Fraysa** [comment]
It was useful for a project of mine which runs the scripts on a different thread and I needed to remove something after the script has executed.

**Comment by viniciusjarina** [comment]
But all these event are called right before the DoFile/String LoadFile/String method finishes..so you could easily wrap this event inside a wrapper class like

     class MyWrapperClass
     {
             Lua lua = new Lua ();
            public EventHandler finishEvent;
             public object [] DoString (...)
             {
                    var res = lua.DoString (params);
                    finishEvent();
                    return res;
             }
       //etc

There is no real win to add this to the library, you are the only one using this feature, so no point adding a feature to be used by only one. :wink:

**Comment by Fraysa** [comment]
I'm using DoFile and I made the event because I'm running DoFile on a thread.

**Pull request closed without merging**
