### PR TITLE
Allow disabling standard libs

### PR DESCRIPTION
**Pull request by Auios**

### CODE REVIEW

**Review by viniciusjarina — CHANGES_REQUESTED** [review]
Why are you removing `AssemblyInfo` ?

**Comment by Auios** [comment]
> 
> 
> Why are you removing `AssemblyInfo` ?

Whoops! I meant to do that in a different branch...
But according to some .Net doc I read, this isn't necessary anymore as of VS 2017.
However, I didn't meant to include this commit in this PR.

**Comment by viniciusjarina** [comment]
I am not sure if this is a good idea. If you don't open any Lua libraries you won't be able to use `math` `package` `table` `string` functions.

I guess what you want to do if you want to prevent people from open files is override stuff like `io` but prevent people from using `table` and `string` might not be the best option

**Comment by Auios** [comment]
> 
> 
> I am not sure if this is a good idea. If you don't open any Lua libraries you won't be able to use `math` `package` `table` `string` functions.
> 
> I guess what you want to do if you want to prevent people from open files is override stuff like `io` but prevent people from using `table` and `string` might not be the best option

I think I want a completely vanilla lua and I can define everything I want in C# and then register those things as classes. Why restrict how people use this? Besides, the default functionality remains. A user would have to deliberately disable the standard libs.

**Comment by viniciusjarina** [comment]
I am not sure if I follow here, users will be unable to stuff like `table` or `string` from Lua.
In any case, maybe you could create the LuaState externally and use the `Lua` ctor that receive the KeraLua.LuaState

**Comment by Auios** [comment]
There can be many reasons for wanting to disable standard libraries, take for example embedded devices where you want to minimize memory footprint.
Also, you may want to swap the standard libraries out with your own.
Regardless, NLua acts as a C# API bridge for KeraLua and it should provide as much access as possible.

**Comment by viniciusjarina** [comment]
Included here https://github.com/NLua/NLua/commit/780d789ffc087cf0083277c2ab88e395531a38a4 , since there was a conflict and I couldn't merge using GH

**Pull request closed without merging**
